Repository datum-cloud/cloud-portal, pull requests merged in 2025-05, with the labels that each got.

#298 feat: manage env variables for workload sandbox
  app/components/select-configmap/select-configmap.tsx
  app/constants/options.ts
  app/features/workload/form/runtime/container-field.tsx
  app/features/workload/form/runtime/container-form.tsx
  app/features/workload/form/runtime/env-field.tsx
  app/features/workload/form/runtime/envs-form.tsx
  app/features/workload/form/runtime/runtime-form.tsx
  app/features/workload/form/stepper-form.tsx
  app/features/workload/form/update-form.tsx
  app/features/workload/helper.ts
  app/resources/control-plane/workloads.control.ts
  app/resources/interfaces/workload.interface.ts
  app/resources/schemas/workload.schema.ts
  app/routes/api+/config+/config-maps+/list.ts
Labels: enhancement

#299 feat: Display FQDN for the gateway
  app/components/text-copy/text-copy.tsx
  app/components/ui/popover.tsx
  app/resources/control-plane/gateways.control.ts
  app/resources/interfaces/gateway.interface.ts
  app/routes/_private+/$orgId+/projects.$projectId+/_connect+/gateways+/_index.tsx
Labels: enhancement

#300 Fixing otel integration
  docker-compose.yml
  otel.ts
Labels: chore

#305 Fix error when editing secrets: options is not iterable
  app/components/ui/popover.tsx
  app/features/secret/form/edit/edit-metadata.tsx
  app/features/secret/form/metadata-form.tsx
Labels: bug

#309 Changing Otel Log level back
  config/base/deployment.yaml
Labels: changelog:ignore

#314 Adding changelog for v0.1.17 release
  CHANGELOG.md
Labels: changelog:ignore

#322 bug: Remove strict 6-character minimum for resource and section names
  app/resources/schemas/metadata.schema.ts
  app/resources/schemas/project.schema.ts
Labels: bug

#344 Adding changelog for v0.1.18 release
  CHANGELOG.md
Labels: changelog:ignore

#347 Filter placements cities by existing locations
  app/components/select-box/select-box.tsx
  app/features/connect/endpoint-slice/endpoint/endpoint-field.tsx
  app/features/connect/endpoint-slice/port/port-field.tsx
  app/features/connect/gateway/listener/listener-field.tsx
  app/features/connect/http-route/rule/backend-ref/backend-ref-field.tsx
  app/features/connect/http-route/rule/filter/url-rewrite-field.tsx
  app/features/connect/http-route/rule/match/path-field.tsx
  app/features/location/form/create-form.tsx
  app/features/location/form/provider/gcp-provider.tsx
  app/features/location/form/select-iata.tsx
  app/features/observe/export-policies/form/sink/prometheus/batch-field.tsx
  app/features/observe/export-policies/form/sink/prometheus/retry-field.tsx
  app/features/observe/export-policies/form/sink/sink-field.tsx
  app/features/observe/export-policies/form/source/source-field.tsx
  app/features/secret/form/keys/key-field.tsx
  app/features/workload/form/placement/placement-field.tsx
  app/features/workload/form/placement/placements-form.tsx
  app/features/workload/form/runtime/env-field.tsx
  app/features/workload/form/stepper-form.tsx
  app/features/workload/form/storage/storage-field.tsx
  app/features/workload/form/update-form.tsx
  app/routes/_private+/$orgId+/projects.$projectId+/locations+/_index.tsx
  app/routes/api+/locations/_index.tsx
  app/routes/api+/projects+/status.ts
Labels: enhancement
